global using FluentAssertions;
global using TechTalk.SpecFlow;
global using Xunit;
global using TechTalk.SpecFlow.Assist;
global using EATestFramework.Driver;
global using EATestFramework.Extensions;
global using ProductAPI.Data;
global using EATestBDD.Page;
global using OpenQA.Selenium;
